Feature/about us
Joserubemn31/cooking--frontend pull request #33
Opened 2021-01-16 01:47 UTC by Joserubemn31

what i did:

- added about us page;
- import this page into app;
- added email svg;

2021-01-16 01:48 UTC, Joserubemn31 commented
resolves #27

2021-01-17 15:23 UTC, lucasgmelo requested changes
good job!!! everything working here! just a little advice, the link on footer to about us is taking me to /quem-somos and not to /about

2021-01-17 15:23 UTC, lucasgmelo commented on src/App.jsx
> +            <Route path="/about">
/about or /quem-somos

2021-01-18 16:53 UTC, lucasgmelo approved these changes

2021-01-18 16:54 UTC, merged